services:
  - type: web
    name: bot-loc-tin-nhan
    runtime: docker
    plan: free
    healthCheckPath: /
    envVars:
      - key: BOT_TOKEN
        sync: false  # Manual input on Render dashboard
      - key: RENDER_EXTERNAL_URL
        fromService:
          type: web
          name: bot-loc-tin-nhan
          property: url
